const clips=[
{tag:'GAME OF THE WEEK',title:'Allen walks it off in overtime',sub:'BUF 34 • KC 31',time:'2:18',theme:'buf',views:'1.2M',desc:'A cinematic BBL replay package of the final drive and overtime winner.'},
{tag:'TOP PLAYS',title:'Week 2: Top 10 plays',sub:'NFL • WEEK 2',time:'6:42',theme:'red',views:'884K',desc:'The catches, hits, runs and throws that defined the week.'},
{tag:'PLAYER SPOTLIGHT',title:'Lamar takes over Baltimore',sub:'BAL 38 • CLE 14',time:'1:54',theme:'bal',views:'642K',desc:'Every explosive Lamar Jackson moment from a dominant afternoon.'},
{tag:'MIC’D UP • BBL UNIVERSE',title:'Inside the Bills–Chiefs classic',sub:'FIELD ACCESS',time:'4:11',theme:'dark',views:'531K',desc:'AI-produced franchise-universe sideline presentation and cinematic recap.'},
{tag:'BREAKDOWN',title:'How Jefferson keeps getting open',sub:'FILM ROOM',time:'3:27',theme:'min',views:'318K',desc:'BBL Film Room breaks down the route details behind another huge week.'},
{tag:'RIVALRY',title:'The story of Bills vs. Chiefs',sub:'BBL ORIGINAL',time:'8:03',theme:'split',views:'1.8M',desc:'A documentary-style chapter tracing the rivalry into another overtime finish.'}
];
export default function Highlights(){return <main className="wrap"><section className="highlightMast"><div><small>BBL VIDEO</small><h1>HIGHLIGHTS</h1><p>Big plays. Full stories. Your franchise brought to life.</p></div><div className="onAir"><i/> BBL VIDEO NETWORK</div></section><section className="featuredVideo"><div className="videoStage"><div className="fieldLines"/><div className="videoPlayerNo">17</div><button className="play">▶</button><div className="videoBug">BBL <span>AI REPLAY</span></div><div className="videoScore"><b>BUF 34</b><span>FINAL / OT</span><b>KC 31</b></div></div><div className="featuredCopy"><div className="eyebrow">FEATURED • GAME OF THE WEEK</div><h2>THE LAST DRIVE</h2><p>Buffalo and Kansas City trade blows until one final overtime possession decides the night. A broadcast-style cinematic recap built for the BBL franchise universe.</p><div className="videoMeta"><b>8:46</b><span>1.9M views</span><span>Week 2</span></div><div className="aiNotice">✦ AI VIDEO SLOT <span>Generated video packages can live here once a video-generation/render pipeline is connected.</span></div></div></section><div className="videoNav"><b>Featured</b><span>Game Highlights</span><span>Top Plays</span><span>Mic’d Up</span><span>Film Room</span><span>BBL Originals</span></div><section className="clipGrid">{clips.map((c,i)=><article className="clipCard" key={c.title}><div className={'clipThumb '+c.theme}><div className="thumbNumber">{i===0?'17':i===2?'8':i===4?'18':''}</div><button>▶</button><small>{c.tag}</small><strong>{c.time}</strong><div className="bblBug">BBL</div></div><div className="clipCopy"><small>{c.sub}</small><h3>{c.title}</h3><p>{c.desc}</p><div><span>{c.views} views</span><b>WATCH ›</b></div></div></article>)}</section><section className="reel"><div><small>BBL QUICK HITS</small><h2>60 SECONDS AROUND THE LEAGUE</h2><p>A vertical-video feed for touchdowns, celebrations, controversy, records and weekly moments.</p></div>{['WALK-OFF','ONE-HANDED','SACKED','SIDELINE'].map((x,i)=><article key={x}><div className="reelNo">{[17,18,11,10][i]}</div><button>▶</button><b>{x}</b><span>0:{[24,18,31,27][i]}</span></article>)}</section></main>}
