const articles=[
{type:'DEVELOPING • BBL UNIVERSE',title:'Dolphins downplay tension after star WR’s postgame comments',dek:'Miami says there is no internal issue, but a six-target afternoon and a terse answer after the loss have created the first real controversy of the season.',time:'12 min ago',theme:'aqua'},
{type:'BBL INSIDER',title:'Trade market begins to move: contenders calling on veteran defenders',dek:'League sources say Seattle has received exploratory calls on a veteran edge rusher while two AFC contenders are monitoring the cornerback market.',time:'41 min ago',theme:'blue'},
{type:'RIVALRY',title:'Bills–Chiefs delivers again — and players admit this one felt different',dek:'Buffalo’s overtime win adds another chapter to the AFC’s marquee matchup. “You know who is across from you,” one Bills veteran said.',time:'1 hr ago',theme:'red'},
{type:'COMMUNITY • BBL UNIVERSE',title:'Justin Jefferson surprises youth program with full equipment donation',dek:'The Minnesota star met players after practice and covered new equipment for more than 100 kids in the program.',time:'2 hrs ago',theme:'purple'},
{type:'INJURY WATCH',title:'49ers optimistic on McCaffrey after late exit',dek:'The early expectation is that the injury is not considered long-term, though his Week 3 status remains worth watching.',time:'3 hrs ago',theme:'gold'},
{type:'FILM ROOM',title:'How Baltimore unlocked Lamar Jackson’s legs again',dek:'Three formation tweaks created easy numbers in the run game and helped Jackson turn broken plays into explosive gains.',time:'4 hrs ago',theme:'black'},
{type:'HOT SEAT',title:'Dallas faces an uncomfortable week after 0–2 start',dek:'Turnovers, protection problems and another fourth-quarter collapse have put the Cowboys under the microscope.',time:'5 hrs ago',theme:'navy'},
{type:'AWARDS',title:'MVP Watch: Allen surges to No. 1 after seven-touchdown start',dek:'Lamar Jackson is close behind while Jalen Hurts and Patrick Mahomes remain firmly in the early race.',time:'6 hrs ago',theme:'red'}];
export default function News(){return <main className="wrap"><div className="newsMast"><div><span>BBL SPORTS</span><h1>NFL NEWSROOM</h1><p>Breaking news, analysis, league buzz and the stories shaping your franchise.</p></div><div className="newsPulse"><b>NEWS PULSE</b><strong>8</strong><span>active stories</span></div></div><div className="newsLayout"><section><article className="newsLead"><div className="newsLeadArt"><span>DEVELOPING</span><b>MIAMI</b><i>87</i></div><div className="newsLeadText"><small>BBL UNIVERSE • 12 MIN AGO</small><h2>One quote. Six targets. Now everyone in Miami is answering questions.</h2><p>The Dolphins insist there is no rift with their star receiver. His postgame answer ensured that Week 3 will begin with scrutiny anyway.</p><div className="quote">“I’m here to win. That’s all I’m going to say.”</div><b>READ FULL STORY →</b></div></article><div className="articleList">{articles.slice(1).map((a,i)=><article className="newsItem" key={a.title}><div className={'newsThumb '+a.theme}><span>{a.type.split(' • ')[0]}</span></div><div><small>{a.type} • {a.time}</small><h2>{a.title}</h2><p>{a.dek}</p><div className="storyMeta">NFL • 2026 Week 2 {a.type.includes('UNIVERSE')?'• FICTIONAL FRANCHISE STORY':''}</div></div></article>)}</div></section><aside><div className="card"><div className="sectiontitle">Top Headlines</div>{articles.slice(0,6).map((a,i)=><div className="sideHeadline" key={a.title}><b>{i+1}</b><span>{a.title}</span></div>)}</div><div className="card rumor"><div className="eyebrow">INSIDER NOTEBOOK</div><h3>League buzz</h3><p><b>SEA:</b> Calls coming in on veteran edge help.</p><p><b>DAL:</b> Front office still backing coaching staff.</p><p><b>MIA:</b> Team expected to make receiver usage a priority.</p><p><b>BUF:</b> Exploring secondary depth after 2–0 start.</p><small>Demo editorial universe</small></div><div className="card"><div className="sectiontitle">Storyline Tracker</div><div className="storyTrack"><b>🔥 Bills–Chiefs rivalry</b><span>Heating up • Week 2</span></div><div className="storyTrack"><b>👀 Miami WR frustration</b><span>Developing • Week 2</span></div><div className="storyTrack"><b>📈 Allen MVP surge</b><span>Rising • Week 2</span></div><div className="storyTrack"><b>⚠ Dallas pressure</b><span>Watch • Week 2</span></div></div></aside></div></main>}
