const cards=[
{tag:'PLAYER OF THE WEEK',title:'STATEMENT MADE',name:'Week\'s top performer',copy:'Automatically generated from the latest imported box scores.',tone:'red'},
{tag:'AWARDS WATCH',title:'MVP LADDER',name:'The race changes every week',copy:'Portrait-led award graphics with stats, movement and BBL model share.',tone:'gold'},
{tag:'BREAKING',title:'BLOCKBUSTER',name:'Trade & transaction graphics',copy:'Major roster moves receive a broadcast-style breaking news card.',tone:'blue'},
{tag:'BBL UNIVERSE',title:'OFF THE FIELD',name:'Community • personality • rivalry',copy:'Clearly labeled fictional franchise-world stories can develop across weeks.',tone:'green'},
{tag:'HISTORY',title:'RECORD BROKEN',name:'Milestones become permanent',copy:'Record graphics link back to the player, game, season and team timeline.',tone:'purple'},
{tag:'GAME OF THE WEEK',title:'PRIME TIME',name:'Matchup posters',copy:'Team-vs-team graphics driven by standings, streaks and rivalry history.',tone:'black'}
];
export default function Media(){return <main className="wrap"><div className="eyebrow">BBL MEDIA NETWORK</div><h1 className="pagehead">Graphics Studio</h1><p className="lede">BBL turns imported franchise events into a visual sports-media feed. Player portraits and team art are attached after Madden player/team IDs are mapped.</p><div className="mediaGrid">{cards.map((c,i)=><article className={'mediaCard '+c.tone} key={i}><div className="mediaTag">{c.tag}</div><div className="mediaWater">BBL</div><div className="portrait"><span>PLAYER<br/>PORTRAIT</span></div><div className="mediaCopy"><h2>{c.title}</h2><h3>{c.name}</h3><p>{c.copy}</p><div className="mediaRule"/></div></article>)}</div><section className="card mediaInfo"><div className="sectiontitle">Automatic graphic triggers</div><div className="triggerGrid"><div><b>Performance</b><span>Huge games, career highs, streaks, breakouts, fantasy explosions</span></div><div><b>Awards</b><span>MVP, OPOY, DPOY, rookies, weekly honors and movement</span></div><div><b>League news</b><span>Trades, signings, releases, playoff clinches and eliminations</span></div><div><b>BBL Universe</b><span>Community stories, harmless controversy, rivalries and personality arcs</span></div><div><b>History</b><span>Records, milestones, championships and franchise timeline moments</span></div><div><b>Games</b><span>Upsets, classics, blowouts, revenge games and playoff matchups</span></div></div></section></main>}
